baseURL: http://example.org/
languageCode: en-us
title: Gustavo
theme: "PaperMod"

params:
  showShareButtons: true
  ShowPostNavLinks: true

  # Menu items
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives
      weight: 3
services:
  googleAnalytics:
    ID: G-1HD65W2C3M
